stages:
  - validate
  - fetch-binaries
  - build
  - extras
  - package
  - upload
  - release

default:
  tags: [shell-executor]

hlint:
  stage: validate
  rules: &if_merge_request
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - nix-shell -p haskellPackages.hlint --run ./scripts/hlint.sh

check-trailing-whitespace:
  stage: validate
  rules: *if_merge_request
  script:
    - ./scripts/check-trailing-whitespace.sh

fetch-linux-binaries:
  stage: fetch-binaries
  rules: *if_merge_request
  script:
    - nix-build dep/serokell-tezos-binaries/build.nix

fetch-macos-binaries:
  stage: fetch-binaries
  rules: *if_merge_request
  script:
    - nix-build dep/brew-tezos-binaries/build.nix

build-kiln:
  stage: build
  rules: *if_merge_request
  script:
    - nix-build -A exe --argstr closure-compiler-setting "BUNDLE" --no-out-link

xrefcheck:
  stage: extras
  rules: *if_merge_request
  allow_failure: true
  script:
    - nix run -f ./dep/xrefcheck -c xrefcheck
  retry:
    max: 2
    when: script_failure

build-docker-image:
  stage: package
  rules: &if_tag
    - if: '$CI_COMMIT_TAG != null'
  script:
    - nix-build -A dockerImage --out-link docker-image
  artifacts:
    paths:
      - docker-image

build-deb-package:
  stage: package
  rules: *if_tag
  script:
    - nix-build -A kiln-debian --out-link debian
  artifacts:
    paths:
      - debian/*

upload-release-artifacts:
  stage: upload
  rules: &if_release_tag
    - if: '$CI_COMMIT_TAG =~ /rc/'
      when: never
    - if: '$CI_COMMIT_TAG != null'
  variables:
    PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/kiln/${CI_COMMIT_TAG}"
    HEADER: "JOB-TOKEN: $CI_JOB_TOKEN"
  needs:
    - build-docker-image
    - build-deb-package
  script:
    - export DEST_CREDS="$CI_REGISTRY_USER":"$CI_REGISTRY_PASSWORD"
    - nix-shell -p skopeo --run 'skopeo --insecure-policy copy --dest-creds "$DEST_CREDS" docker-archive:./docker-image docker://"$CI_REGISTRY_IMAGE":"$CI_COMMIT_TAG"'
    - export DEB_PACKAGE_NAME="$(basename "$(ls ./debian/*.deb)")"
    - nix-shell -p curl --run 'curl --header "$HEADER" --upload-file "./debian/$DEB_PACKAGE_NAME" "$PACKAGE_REGISTRY_URL/$DEB_PACKAGE_NAME"'
    - echo "DEB_PACKAGE_NAME=$DEB_PACKAGE_NAME" >> build.env
  artifacts:
    reports:
      dotenv: build.env

create-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli
  needs:
    - upload-release-artifacts
  tags: []
  rules: *if_release_tag
  variables:
    PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/kiln/${CI_COMMIT_TAG}"
  script:
    - >
      deb_asset="{\"name\": \"Debian/Ubuntu\", \"url\": \"$PACKAGE_REGISTRY_URL/$DEB_PACKAGE_NAME\"}"
    - >
      release-cli create --name "$CI_COMMIT_TAG" --tag-name "$CI_COMMIT_TAG" --assets-link="$deb_asset"
