name: tezos-bake-monitor-lib
version: 0.1.0.0
synopsis: Shared types and code between tezos-bake-monitor and tezos-bake-central.
-- description:
license: BSD3
license-file: LICENSE
author: Obsidian Systems LLC
maintainer: maintainer@obsidian.systems
-- copyright:
-- category:
build-type: Simple
extra-source-files: CHANGELOG.md
cabal-version: >=1.10

library
  exposed-modules:
    -- Tezos.NodeRPC.Schema
    Data.LCA.Online.Polymorphic
    Tezos.Account
    Tezos.BalanceUpdate
    Tezos.Base16ByteString
    Tezos.Base58Check
    Tezos.Binary
    Tezos.Block
    Tezos.BlockHeader
    Tezos.Chain
    Tezos.Checkpoint
    Tezos.Contract
    Tezos.Envelope
    Tezos.Fitness
    Tezos.Json
    Tezos.Lenses
    Tezos.Ledger
    Tezos.Level
    Tezos.Micheline
    Tezos.Michelson
    Tezos.NodeRPC.Class
    Tezos.NodeRPC.Sources
    Tezos.NodeRPC.Types
    Tezos.Operation
    Tezos.PeriodSequence
    Tezos.ProtocolConstants
    Tezos.PublicKey
    Tezos.PublicKeyHash
    Tezos.Signature
    Tezos.ShortByteString
    Tezos.TestChainStatus
    Tezos.Tez
    Tezos.Types
    Tezos.Vote
  other-modules:
    Paths_tezos_bake_monitor_lib
  build-depends:
      base
    , aeson
    , async
    , binary
    , base16-bytestring
    , base58-bytestring
    , bytestring
    , cases
    , containers
    , cryptohash
    , cryptonite
    , deepseq
    , dependent-sum
    , functor-infix
    , groups
    , hashable
    , hashing
    , http-types
    , lens
    , memory
    , modern-uri
    , mtl
    , process
    , safe
    , safe-exceptions
    , scientific
    , semigroups
    , tagged
    , template-haskell
    , text
    , time
    , unordered-containers
    , vector
  hs-source-dirs: src
  default-language: Haskell2010
  ghc-options: -Wall -Werror
