name: frontend
version: 0.1
license: BSD3
copyright: Copyright (C) Obsidian Systems LLC 2018
author: Obsidian Systems LLC
maintainer: maintainer@obsidian.systems
stability: Experimental
build-type: Simple
cabal-version: >=1.8

library
  hs-source-dirs: src

  exposed-modules:
    Frontend

  other-modules:
    Frontend.Common

  build-depends:
      base
    , base16-bytestring
    , bytestring
    , common
    , containers
    , data-default
    , either
    , file-embed
    , ghcjs-dom
    , IntervalMap
    , lens
    , modern-uri
    , mtl
    , obelisk-executable-config
    , reflex
    , reflex-dom-core
    , reflex-dom-forms
    , rhyolite-common
    , rhyolite-frontend
    , safe
    , semantic-reflex
    , text
    , tezos-bake-monitor-lib
    , these
    , time

  ghc-options: -Wall -fno-warn-unused-do-bind -fwarn-tabs -funbox-strict-fields -O2 -fprof-auto-calls -rtsopts -fexpose-all-unfoldings

executable frontend
  main-is: Main.hs
  hs-source-dirs: src-bin
  build-depends:
      base
    , frontend
    , reflex-dom
  ghc-options: -threaded
  if os(darwin)
     ghc-options: -dynamic
