name: common
version: 0.1
license: BSD3
copyright: Copyright (C) Obsidian Systems LLC 2018
author: Obsidian Systems LLC
maintainer: maintainer@obsidian.systems
stability: Experimental
build-type: Simple
cabal-version: >=1.8

flag docker
  description: Is being built for docker
  default: False

flag linux-package
  description: Is being built for a Linux package (Debian, Redhat, etc.)
  default: False

library
  hs-source-dirs: src

  build-depends:
      aeson
    , IntervalMap
    , attoparsec
    , base
    , base16-bytestring
    , base58-bytestring
    , bytestring
    , cases
    , constraints
    , constraints-extras
    , containers
    , cryptohash
    , cryptonite
    , data-default
    , database-id-class
    , dependent-map
    , dependent-sum
    , dependent-sum-aeson-orphans
    , dependent-sum-template
    , either
    , file-embed
    , hashing
    , lens
    , memory
    , modern-uri
    , monoidal-containers
    , mtl
    , obelisk-generated-static
    , obelisk-route
    , reflection
    , reflex
    , reflex-dom-core
    , rhyolite-common
    , rhyolite-datastructures
    , rhyolite-frontend
    , safe-exceptions
    , scientific
    , split
    , template-haskell
    , text
    , tezos-bake-monitor-lib
    , these
    , time
    , transformers-compat
    , universe
    , universe-base
    , universe-dependent-sum
    , unordered-containers
    , uri-encode
    , witherable
    , writer-cps-mtl

  exposed-modules:
    Common
    Common.Alerts
    Common.Api
    Common.App
    Common.AppendIntervalMap
    Common.Calculations
    Common.Config
    Common.Distribution
    Common.HeadTag
    Common.Route
    Common.Schema
    Common.URI
    Common.Vassal
    Common.Verification
    Common.WrappedShow1
    ExtraPrelude

  ghc-options: -Wall -fno-warn-unused-do-bind -fwarn-tabs -funbox-strict-fields -O2 -fprof-auto-calls -fexpose-all-unfoldings

  if flag(docker)
    cpp-options: -DDISTRO_DOCKER
  else
    if flag(linux-package)
      cpp-options: -DDISTRO_LINUX_PACKAGE
