name: backend
version: 0.2.3
license: BSD3
copyright: Copyright (C) Obsidian Systems LLC 2018
author: Obsidian Systems LLC
maintainer: maintainer@obsidian.systems
stability: Experimental
build-type: Simple
cabal-version: >=1.8

library
  hs-source-dirs: src

  build-depends:
      aeson
    , async
    , backend-db
    , base
    , base16-bytestring
    , bytestring
    -- , Chart
    -- , Chart-diagrams
    , clientsession
    , colour
    , common
    , constraints
    , containers
    , data-default
    , dependent-map
    , dependent-sum
    , dependent-sum-template
    -- , diagrams-core
    -- , diagrams-lib
    -- , diagrams-svg
    , exceptions
    , filepath
    , formatting
    , frontend
    , functor-infix
    , generic-deriving
    , groundhog
    , groundhog-postgresql
    , groundhog-th
    , hashable
    , http-client
    , http-client-tls
    , http-conduit
    , http-types
    , IntervalMap
    , lens
    , mime-mail
    , modern-uri
    , monad-control
    , monad-logger
    , monoidal-containers
    , mtl
    , network
    , obelisk-asset-serve-snap
    , obelisk-backend
    , obelisk-backend
    , obelisk-executable-config-inject
    , obelisk-frontend
    , obelisk-route
    , postgresql-simple
    , random-extras
    , random-fu
    , reflex
    , reflex-dom-core
    , resource-pool
    , rhyolite-backend
    , rhyolite-backend-db
    , rhyolite-backend-snap
    , rhyolite-common
    , safe
    , safe-exceptions
    , snap-core
    , snap-loader-static
    , snap-server
    , stm
    , svg-builder
    , text
    , tezos-bake-monitor-lib
    , tezos-noderpc
    , time
    , transformers
    , unix
    , uri-encode

  exposed-modules:
    Backend

  other-modules:
    Paths_backend
    Backend.Alerts
    Backend.Alerts.Common
    Backend.BalanceTracking
    Backend.CachedNodeRPC
    Backend.ChainHealth
    Backend.Common
    Backend.Config
    --Backend.Graphs
    Backend.Http
    Backend.Migrations
    Backend.NotifyHandler
    Backend.RequestHandler
    Backend.Schema
    Backend.STM
    Backend.Supervisor
    Backend.Telegram
    Backend.Upgrade
    Backend.Version
    Backend.ViewSelectorHandler
    Backend.WebApi
    Backend.Workers.Cache
    Backend.Workers.Client
    Backend.Workers.Baker
    Backend.Workers.Node

  ghc-options: -Wall -fno-warn-unused-do-bind -fwarn-tabs -funbox-strict-fields -O2 -fprof-auto-calls -fexpose-all-unfoldings
  cpp-options: -DREAL_BUILD

executable backend
  hs-source-dirs: src-bin
  main-is: Main.hs

  build-depends:
      base
    , backend
    , obelisk-backend

  ghc-options: -threaded -Wall -fno-warn-unused-do-bind -fwarn-tabs -funbox-strict-fields -O2 -fprof-auto-calls -rtsopts -fexpose-all-unfoldings
