name: backend
version: 0.1
license: BSD3
copyright: Copyright (C) Obsidian Systems LLC 2018
author: Obsidian Systems LLC
maintainer: maintainer@obsidian.systems
stability: Experimental
build-type: Simple
cabal-version: >=1.8

library
  hs-source-dirs: src

  build-depends:
      aeson
    , base
    , base16-bytestring
    , bytestring
    , Chart
    , Chart-diagrams
    , clientsession
    , colour
    , common
    , containers
    , constraints
    , data-default
    , dependent-map
    , dependent-sum-template
    , diagrams-core
    , diagrams-lib
    , diagrams-svg
    , either
    , filepath
    , formatting
    , frontend
    , generic-deriving
    , groundhog
    , groundhog-postgresql
    , groundhog-th
    , http-client
    , http-client-tls
    , http-conduit
    , http-types
    , lens
    , lens-aeson
    , mime-mail
    , modern-uri
    , monad-control
    , monad-logger
    , mtl
    , network
    , obelisk-asset-serve-snap
    , obelisk-executable-config-inject
    , postgresql-simple
    , reflex
    , reflex-dom-core
    , resource-pool
    , rhyolite-backend
    , rhyolite-backend-snap
    , rhyolite-common
    , safe
    , safe-exceptions
    , say
    , snap-core
    , snap-loader-static
    , snap-server
    , stm
    , svg-builder
    , text
    , tezos-bake-monitor-lib
    , time

  exposed-modules:
    Backend

  other-modules:
    Paths_backend
    Backend.BalanceTracking
    Backend.CachedNodeRPC
    Backend.ChainHealth
    Backend.Common
    Backend.Config
    Backend.Errors
    Backend.Graphs
    Backend.NotifyHandler
    Backend.RequestHandler
    Backend.Schema
    Backend.Upgrade
    Backend.Version
    Backend.ViewSelectorHandler
    Backend.Workers
    Backend.Workers.Client
    Backend.Workers.Delegate
    Backend.Workers.Node

  ghc-options: -Wall -fno-warn-unused-do-bind -fwarn-tabs -funbox-strict-fields -O2 -fprof-auto-calls -rtsopts -fexpose-all-unfoldings
               -DREAL_BUILD

executable backend
  hs-source-dirs: src-bin
  main-is: Main.hs

  build-depends:
      base
    , backend

  ghc-options: -threaded -Wall -fno-warn-unused-do-bind -fwarn-tabs -funbox-strict-fields -O2 -fprof-auto-calls -rtsopts -fexpose-all-unfoldings
